apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    server: 172.23.0.239 #NFS服务器内网ip
    path: /opt/nfs_logs #NFS共享目录